server:
  port: 84

spring:
  application:
    name: nacos-order-consumer

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        #默认是8719端口，如果被占用，自动从8719开始依次+1扫描，直到找到未被占用的
        port: 8719
        #配置sentinel dashboard地址
        dashboard: localhost:8080

  management:
    endpoints:
      web:
        exposure:
          include: "*"
#消费者将要访问的微服务名称(注册成功进nacos的微服务提供者)
service-url:
  nacos-user-service: http://nacos-payment-provider
feign:
  sentinel:
    enabled: true #激活sentinel对feign的支持