server:
  port: 8001
spring:
  application:
    name: cloud-payment-service
    #链路追踪相关配置
  zipkin:
      base-url: http://localhost:9411
  sleuth:
      sampler:
        # 采样值介于0，1之间，1则表示全部采集
        probability: 1


  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name:  com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud2020?useUnicode=true&allowPublicKeyRetrieval=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 1460088689


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: xyz.zhguang.springcloud.entities #所有entities别名类所在包

eureka:
  client:
    #表示是否将自己注册进eurekaServer里面，默认true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka   #单机
#      defaultZone: http://eureka7002.com:7002/eureka,http://eureka7001.com:7001/eureka
  instance:
    instance-id: payment8001 #在eureka注册中的application的status栏，不显示主机名称，只显示这个
    prefer-ip-address: true #浏览器左下脚显示Ip
#    eureka客户端向服务端发送心跳的间隔时间，默认30s
    lease-renewal-interval-in-seconds: 1
#    eureka服务端在收到最后一次心跳后的等待时间上限，默认90，超时将剔除服务
    lease-expiration-duration-in-seconds: 2