server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: payment_routh #payment_route 路由id,没有固定规则，但要求唯一，建议配合服务名
#          uri: http://localhost:8001 #匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/** #断言，路径相匹配的进行路由
        - id: payment_routh2
#          uri: http://localhost:8001
          uri: lb://CLOUD-PAYMENT-SERVICE #负载？？
          predicates:
            - Path=/payment/lb/**
            - After=2021-06-20T09:45:47.723+08:00[Asia/Shanghai] #该路由要在此时间点后才能访问，否则404，类似的还有After,Between
#            - Cookie=username,loocc #不携带指定键值对的cookie就404
#            - Header=X-Request-Id, \d+ #请求头带有X-Request-Id并且值为整数的正则表达式
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    hostname: cloud-gateway-service