server:
  port: 80
eureka:
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
#     当服务端有耗时接口时，需要设置这个
#  设置feign客户端的超时时间，openfeign默认支持ribbon
ribbon:
  #指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间
  ReadTimeout: 5000
  #指连接建立成功后，从服务器读取到可用资源所用时间
  ConnectTimeout: 5000
logging:
  level:
    #feign日志以什么级别监控哪个接口，以debug级别打印FULL全日志
    xyz.zhguang.springcloud.service.PaymentFeignService: debug